Comcast_Region
,NAX_Building_ID
,Engagement_ID
,Probability
,Business_Name
,Building_Address
,Building_City
,Building_State
,Building_Zip
,Oppty_Status
,Order_Status
,Order_Type
,Survey_Request_Type
,Survey_Status
,MIP_LAT
,MIP_LONG
,MIP_Sellability_Color_Coax
,IQ_ISP_Cost
,IQ_Coax_Cost
,Survey_Construction_Cost
,Order_Created_Date
,OA_Complete_Date
,ROE_Created_Date
,Oppty_ID
,Oppty_ID2
,Sales_Rep
,Sales_Channel
,Bundle_Name
,PreSurvey_Start
,PreSurvey_End
,PreSurvey_Task_Owner
,x_exterior_type
,Transport_Type
,Workbench_ID
,Proposed_SmartBuild --contains list of building ids
